-- Import the data from airline_call_transcripts.csv to CORTEX_AI_DB.PUBLIC.AIRLINE_CALL_TRANSCRIPTS

-- Create table that stores the translated transcripts and summary

SELECT *, 
  SNOWFLAKE.CORTEX.TRANSLATE (CALL_TRANSCRIPT,'','en') TRANSLATED_TRANSCRIPT, 
  SNOWFLAKE.CORTEX.SUMMARIZE(TRANSLATED_TRANSCRIPT) TRANSCRIPT_SUMMARY
  FROM AIRLINE_CALL_TRANSCRIPTS;

-- Query the table

  SELECT * FROM AIRLINE_TRANSLATED_CALL_TRANSCRIPTS;