--CORTEX_FUNCTIONS_USAGE_HISTORY
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FUNCTIONS_USAGE_HISTORY;

-- CORTEX_FUNCTIONS_QUERY_USAGE_HISTORY
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FUNCTIONS_QUERY_USAGE_HISTORY;

-- METERING_DAILY_HISTORY
SELECT * 
FROM  SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE SERVICE_TYPE ='AI_SERVICES';

-- METERING_HISTORY
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY;

-- METERING_HISTORY FILTERED AND GROUPED ON AI SERVICES
SELECT 
    START_TIME::TIMESTAMP AS EXECUTION_START_TIME,
    SUM(CREDITS_USED) CONSUMED_CREDITS,
    SERVICE_TYPE
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE SERVICE_TYPE='AI_SERVICES'
GROUP BY 
    EXECUTION_START_TIME, SERVICE_TYPE
ORDER BY 
    CONSUMED_CREDITS DESC;

-- ACCESS_HISTORY table complements User-Based Access Control (UBAC) by recording user access

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY;

    
